import {apiClient} from "@/lib/api/client";
import type {ContentDetail,ContentQuery,ContentRepository,ContentSummary,ContentType} from "./types";
interface ApiItem {id:string;type:ContentType;stableKey:string;title:string;category:string;status:string;version:number;availabilityState?:"restricted"|"pilot"|"published";reviewStatus?:string;migrationState?:string;requiresReview?:boolean;aiEligible?:boolean;reviewReason?:string;bodyJson?:{body?:string;tags?:string[];legacyPayload?:Record<string,unknown>;sourceRef?:ContentDetail["sourceRef"];legacyId?:string};sourceHash?:string;}
function summary(item:ApiItem):ContentSummary{return{id:item.id,legacyId:item.bodyJson?.legacyId??item.stableKey,type:item.type,category:item.category,title:item.title,tags:item.bodyJson?.tags??[],publicationState:item.status,availabilityState:item.availabilityState,reviewStatus:item.reviewStatus,migrationState:item.migrationState,requiresReview:item.requiresReview,aiEligible:item.aiEligible};}
export class RemoteContentRepository implements ContentRepository{
  async counts(){const types:ContentType[]=["talk","flow","glossary","price","manual","legal","video","roleplay"];const pairs=await Promise.all(types.map(async type=>{const result=await this.search({type:[type],page:1,pageSize:1});return[type,result.total] as const;}));return Object.fromEntries(pairs) as Record<ContentType,number>;}
  async search(query:ContentQuery){const params=new URLSearchParams({limit:String(query.pageSize)});if(query.type?.length)params.set("type",query.type.join(","));if(query.text)params.set("query",query.text);let cursor:string|undefined;let result:{items:ApiItem[];total:number;nextCursor:string|null;hasMore:boolean}={items:[],total:0,nextCursor:null,hasMore:false};for(let page=1;page<=query.page;page+=1){if(cursor)params.set("cursor",cursor);else params.delete("cursor");result=await apiClient.request(`/contents?${params}`);if(page<query.page){if(!result.nextCursor)return{items:[],total:result.total,hasMore:false};cursor=result.nextCursor;}}return{items:result.items.map(summary),total:result.total,hasMore:result.hasMore};}
  async get(id:string){const item=await apiClient.request<ApiItem>(`/contents/${encodeURIComponent(id)}`);const base=summary(item);return{...base,version:item.version,body:item.bodyJson?.body??"",legacyPayload:item.bodyJson?.legacyPayload??{},sourceRef:item.bodyJson?.sourceRef??{repository:"database",file:"content_versions",variable:null,captured_at:"",source_sha256:item.sourceHash??""},originalHash:item.sourceHash??"",migrationState:item.migrationState??"not_applicable",reviewReason:item.reviewReason??""};}
  async related(id:string,limit:number){const current=await this.get(id);const found=await this.search({type:[current.type],category:[current.category],page:1,pageSize:limit+1});return found.items.filter(item=>item.id!==id).slice(0,limit);}
}
