import {ApiClientError,apiClient} from "./client";
import {sha256Blob} from "@/lib/files/sha256";
import {recordingConsentNoticeVersion,type OperationsHealthDto,type RetentionBindingDto,type TranscriptQualityAssessment,type TranscriptQualityFlag} from "@hanamaru/contracts";
export type {OperationsHealthDto,RetentionBindingDto,TranscriptQualityFlag};
export type TranscriptQualityAssessmentDto=TranscriptQualityAssessment;

export interface VisitDto {id:string;caseNumber:string;status:string;visitDate:string|null;visitTime:string|null;timeZone:"Asia/Tokyo";scheduledAt:string|null;customerLabel:string|null;branchName?:string;branchId:string;lockVersion:number;}
export interface JobAttemptDto {attemptNo:number;startedAt:string;finishedAt:string|null;resultStatus:string|null;errorCode:string|null;}
export interface JobDto {id:string;jobType:string;status:string;entityType:string;entityId:string;attemptCount:number;maxAttempts:number;errorCode:string|null;createdAt:string;finishedAt:string|null;attempts?:JobAttemptDto[];resultResource?:{type:string;id:string;href:string}|null;}
export interface FieldDto {id:string;fieldKey:string;valueType:string;textValue:string|null;numberValue:number|null;dateValue:string|null;booleanValue:boolean|null;jsonValue:unknown;sourcePage:number|null;sourceExcerpt:string|null;confidence:number|null;verificationStatus:string;}
export interface TranscriptSegmentDto {id:string;sequenceNo:number;startMs:number;endMs:number;speakerLabel:string|null;speakerRole:"staff"|"customer"|"unknown";text:string;editedText:string|null;confidence:number|null;}
export interface FindingDto {id:string;category:string;title:string;description:string;recommendedAction:string|null;evidence:Array<{segmentId:string;excerpt:string}>;}
export interface VisitWorkspaceDto {visit:VisitDto;document:null|{id:string;status:string};extraction:null|{id:string;status:string;lockVersion:number};fields:FieldDto[];recording:null|{id:string;status:string;durationMs:number|null};transcript:null|{id:string;status:string;lockVersion:number;fullText:string};qualityAssessment:TranscriptQualityAssessmentDto|null;segments:TranscriptSegmentDto[];review:null|{id:string;status:string;lockVersion:number;summary:string};findings:FindingDto[];consent:null|{id:string;status:string;noticeVersion:string};jobs:JobDto[];}
export interface UserDto {id:string;branchId:string;status:string;lockVersion:number;displayName:string;emailMasked:string;roles:string[];}
export interface HistoryDto {reviewId:string;reviewStatus:string;summary:string;createdAt:string;visitId:string;caseNumber:string;scheduledAt:string|null;}
export interface AuditDto {id:string;occurredAt:string;action:string;result:string;requestId:string;resourceType:string;resourceId:string|null;}
export interface DeletionDto {id:string;visitId:string;requestType:string;reasonCode:string;status:string;requestedAt:string;completedAt:string|null;jobId:string|null;}
export interface ContentPolicyDto {mode:"pilot"|"published";pilotContentEnabled:boolean;usesUnapprovedContent:boolean;requiresHumanReview:boolean;contentIds:string[];contentVersionIds:string[];policyNoticeVersion:string;notice:string|null;}
export interface PreparationDto {id:string;visitId:string;status:"generated"|"confirmed";version:number;lockVersion:number;modelName:string;structuredResult:{customerFacts:Array<{label:string;value:string;sourceFieldKey:string|null}>;anticipatedPsychology:Array<{title:string;description:string;basisFieldKeys:string[]}>;legalChecks:Array<{title:string;description:string;sourceContentIds:string[]}>;suggestedTalks:Array<{title:string;script:string;sourceContentIds:string[]}>;anticipatedQuestions:Array<{question:string;answer:string;sourceContentIds:string[]}>;contentPolicy:ContentPolicyDto;};}
export interface RetentionPolicyDto {id:string;dataType:string;version:number;retentionDays:number;legalHoldSupported:boolean;status:string;effectiveFrom:string;}
export interface RoleplaySessionDto {id:string;status:"active"|"completed";startedAt:string;completedAt:string|null;selfNote:string|null;scenarioId:string;title:string;turnCount:number;}
export interface RoleplaySessionDetailDto {id:string;status:"active"|"completed";scenarioContentItemId:string;scenarioTitle:string;selfNote:string|null;turns:Array<{id:string;sequenceNo:number;staffText:string;customerReply:string;feedback:Array<{category:string;message:string}>;createdAt:string}>;}
export interface ApprovalDto {id:string;title:string;type:string;versionId:string;version:number;bodyJson:Record<string,unknown>;changeSummary:string|null;previousVersionId:string|null;previousVersion:number|null;previousBodyJson:Record<string,unknown>|null;selfAuthored:boolean;}
export interface ApprovalBatchDto {id:string;type:string;category:string;status:"in_review"|"approved"|"rejected"|"invalidated";itemCount:number;requiredApprovals:number;approvalCount:number;snapshotHash:string;submittedAt:string;decidedAt:string|null;selfSubmitted:boolean;items:Array<{id:string;versionId:string;version:number;sourceHash:string;title:string}>;decisions:Array<{decision:"approved"|"rejected";reason:string;decidedAt:string;decidedBy:string}>;}
export interface ApprovalCandidateDto {type:string;category:string;itemCount:number;requiredApprovals:number;}
export interface FeatureFlagDto {flagKey:"pilot_content_ai"|"content_approval"|"team_analytics";enabled:boolean;rollbackNote:string;updatedAt:string;}

type List<T>={items:T[];hasMore:boolean;nextCursor:string|null;total?:number};
async function upload(path:string,file:File,extra:Record<string,unknown>={}){const sha256=await sha256Blob(file);const session=await apiClient.request<{uploadId:string;url:string;method:"PUT";headers:Record<string,string>}>(path,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({mimeType:file.type||"application/octet-stream",sizeBytes:file.size,sha256,...extra})});const url=apiClient.resolveUrl(session.url);const headers=await apiClient.uploadHeadersFor(url,session.headers);const response=await fetch(url,{method:session.method,headers,body:file,credentials:"omit"});if(!response.ok)throw new Error("ファイルをアップロードできませんでした");return session;}
async function putUpload(session:{url:string;method:"PUT";headers:Record<string,string>},file:File){const url=apiClient.resolveUrl(session.url);const headers=await apiClient.uploadHeadersFor(url,session.headers);const response=await fetch(url,{method:session.method,headers,body:file,credentials:"omit"});if(!response.ok)throw new Error("ファイルをアップロードできませんでした");}
async function putUploadStream(session:{url:string;method:"PUT";headers:Record<string,string>},body:ReadableStream<Uint8Array>){const url=apiClient.resolveUrl(session.url);const headers=await apiClient.uploadHeadersFor(url,session.headers);const init:RequestInit&{duplex:"half"}={method:session.method,headers,body,credentials:"omit",duplex:"half"};const response=await fetch(url,init);if(!response.ok)throw new Error("ファイルをアップロードできませんでした");}

export const resources={
  dashboard:()=>apiClient.request<{visits:VisitDto[];jobs:JobDto[]}>("/dashboard"),
  assistAnswer:(question:string)=>apiClient.request<{answer:string;citations:Array<{id:string;versionId:string;type:string;title:string;availabilityState:"pilot"|"published";requiresReview:boolean}>;suggestedQuestions:string[];model:string;requestId:string;grounded:boolean;contentPolicy:ContentPolicyDto}>("/assist/answers",{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({question})}),
  visits:(query="")=>apiClient.request<List<VisitDto>>(`/visits${query?`?query=${encodeURIComponent(query)}`:""}`),
  visit:(id:string)=>apiClient.request<VisitDto>(`/visits/${id}`),
  workspace:(id:string)=>apiClient.request<VisitWorkspaceDto>(`/visits/${id}/workspace`),
  protectedFileAccess:(kind:"document"|"recording",id:string)=>apiClient.request<{url:string;expiresAt:string|null;requiresBearer:boolean}>(`/${kind}s/${id}/file-access`),
  protectedFileBlob:(path:string)=>apiClient.blob(path),
  createVisit:(body:Record<string,unknown>)=>apiClient.request<VisitDto>("/visits",{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  updateVisit:(id:string,body:Record<string,unknown>)=>apiClient.request<VisitDto>(`/visits/${id}`,{method:"PATCH",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  async importVisitFromPdf(file:File){const sha256=await sha256Blob(file);const session=await apiClient.request<{visitId:string;caseNumber:string;uploadId:string;url:string;method:"PUT";headers:Record<string,string>}>("/visit-imports",{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({mimeType:file.type||"application/octet-stream",sizeBytes:file.size,sha256})});await putUpload(session,file);const document=await apiClient.request<{id:string}>(`/document-uploads/${session.uploadId}/complete`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:"{}"});const job=await apiClient.request<{jobId:string;statusUrl:string}>(`/documents/${document.id}/extractions`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({schemaKey:"visit_info"})});return{visitId:session.visitId,caseNumber:session.caseNumber,...job};},
  async uploadDocument(visitId:string,file:File){const session=await upload(`/visits/${visitId}/documents/uploads`,file);const document=await apiClient.request<{id:string}>(`/document-uploads/${session.uploadId}/complete`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:"{}"});return apiClient.request<{jobId:string;statusUrl:string}>(`/documents/${document.id}/extractions`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({schemaKey:"visit_info"})});},
  requestExtraction:(documentId:string)=>apiClient.request<{jobId:string;statusUrl:string}>(`/documents/${documentId}/extractions`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({schemaKey:"visit_info"})}),
  updateExtraction:(id:string,expectedLockVersion:number,fields:Array<{fieldKey:string;valueType:string;value:unknown}>)=>apiClient.request<{lockVersion:number}>(`/extractions/${id}`,{method:"PATCH",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({expectedLockVersion,fields})}),
  confirmExtraction:(id:string,expectedLockVersion:number)=>apiClient.request(`/extractions/${id}/confirm`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({expectedLockVersion})}),
  async preparation(visitId:string){try{return await apiClient.request<PreparationDto>(`/visits/${visitId}/preparation`);}catch(error){if(error instanceof ApiClientError&&error.status===404)return null;throw error;}},
  requestPreparation:(visitId:string)=>apiClient.request<{jobId:string;status:string;statusUrl:string}>(`/visits/${visitId}/preparation`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({})}),
  confirmPreparation:(visitId:string,expectedLockVersion:number)=>apiClient.request<PreparationDto>(`/visits/${visitId}/preparation/confirm`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({expectedLockVersion})}),
  consent:(visitId:string)=>apiClient.request<{id:string}>(`/visits/${visitId}/recording-consents`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({status:"granted",method:"verbal",noticeVersion:recordingConsentNoticeVersion})}),
  async uploadRecording(visitId:string,file:File,consentId:string,metadata:{capturedAt:string;durationMs:number|null}){const session=await upload(`/visits/${visitId}/recordings/uploads`,file,{consentId});const recording=await apiClient.request<{id:string}>(`/recording-uploads/${session.uploadId}/complete`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(metadata)});return apiClient.request<{jobId:string;statusUrl:string}>(`/recordings/${recording.id}/transcriptions`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({languageCode:"ja-JP"})});},
  async uploadRecordingStream(visitId:string,input:{mimeType:string;sizeBytes:number;sha256:string;body:ReadableStream<Uint8Array>},consentId:string,metadata:{capturedAt:string;durationMs:number|null}){const session=await apiClient.request<{uploadId:string;url:string;method:"PUT";headers:Record<string,string>}>(`/visits/${visitId}/recordings/uploads`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({mimeType:input.mimeType,sizeBytes:input.sizeBytes,sha256:input.sha256,consentId})});await putUploadStream(session,input.body);const recording=await apiClient.request<{id:string}>(`/recording-uploads/${session.uploadId}/complete`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(metadata)});return apiClient.request<{jobId:string;statusUrl:string}>(`/recordings/${recording.id}/transcriptions`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({languageCode:"ja-JP"})});},
  requestTranscription:(recordingId:string)=>apiClient.request<{jobId:string;statusUrl:string}>(`/recordings/${recordingId}/transcriptions`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({languageCode:"ja-JP"})}),
  acknowledgeTranscriptQuality:(transcriptId:string,decision:"continue"|"replace",lockVersion:number)=>apiClient.request<TranscriptQualityAssessmentDto>(`/transcripts/${transcriptId}/quality-assessment/acknowledgements`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({decision,lockVersion})}),
  confirmTranscript:(id:string,expectedLockVersion:number,segments:Array<{id:string;text:string;speakerRole:"staff"|"customer"|"unknown"}>)=>apiClient.request<{lockVersion:number}>(`/transcripts/${id}`,{method:"PATCH",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({expectedLockVersion,segments})}).then(updated=>apiClient.request(`/transcripts/${id}/confirm`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({expectedLockVersion:updated.lockVersion})})),
  requestReview:(transcriptId:string,objective:string)=>apiClient.request<{jobId:string}>(`/transcripts/${transcriptId}/reviews`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({objective})}),
  createManualTranscript:(visitId:string,text:string)=>apiClient.request<{id:string;status:"confirmed";sourceType:"manual";lineCount:number}>(`/visits/${visitId}/manual-transcripts`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({text})}),
  acknowledgeReview:(id:string,expectedLockVersion:number)=>apiClient.request(`/reviews/${id}/acknowledgements`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({expectedLockVersion})}),
  job:(id:string)=>apiClient.request<JobDto>(`/jobs/${id}`),
  history:()=>apiClient.request<List<HistoryDto>>("/history"),
  users:()=>apiClient.request<List<UserDto>>("/admin/users"),
  inviteUser:(body:Record<string,unknown>)=>apiClient.request<UserDto>("/admin/users",{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  updateUser:(id:string,body:Record<string,unknown>)=>apiClient.request<UserDto>(`/admin/users/${id}`,{method:"PATCH",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  replaceRoles:(id:string,body:Record<string,unknown>)=>apiClient.request(`/admin/users/${id}/roles`,{method:"PUT",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  jobs:()=>apiClient.request<List<JobDto>>("/admin/jobs"),
  deletions:()=>apiClient.request<List<DeletionDto>>("/admin/deletion-requests"),
  requestDeletion:(visitId:string,reasonCode:string)=>apiClient.request<DeletionDto>(`/visits/${visitId}/deletion-requests`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({requestType:"admin",reasonCode})}),
  audits:()=>apiClient.request<List<AuditDto>>("/admin/audit-events"),
  featureFlags:()=>apiClient.request<List<FeatureFlagDto>>("/admin/feature-flags"),
  updateFeatureFlag:(flagKey:string,enabled:boolean,reason:string)=>apiClient.request<FeatureFlagDto>(`/admin/feature-flags/${flagKey}`,{method:"PATCH",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({enabled,reason})}),
  createContent:(body:Record<string,unknown>)=>apiClient.request<{id:string;versionId:string;version:number}>("/contents",{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  updateContent:(id:string,body:Record<string,unknown>)=>apiClient.request<{id:string;versionId:string;version:number}>(`/contents/${id}`,{method:"PATCH",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  async uploadTrainingVideo(contentId:string,versionId:string,file:File){const session=await upload(`/contents/${contentId}/video-uploads`,file,{versionId});return apiClient.request<{id:string;durationMs:number;width:number;height:number}>(`/video-uploads/${session.uploadId}/complete`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:"{}"});},
  trainingVideoAccess:(contentId:string)=>apiClient.request<{url:string;expiresAt:string|null;requiresBearer:boolean}>(`/training/videos/${contentId}/file-access`),
  publishContent:(id:string,version:number)=>apiClient.request(`/contents/${id}/publish`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({version})}),
  retryJob:(id:string)=>apiClient.request(`/admin/jobs/${id}/retry`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({reason:"管理画面から再試行"})}),
  cancelJob:(id:string)=>apiClient.request(`/admin/jobs/${id}/cancel`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({reason:"管理画面から取消"})}),
  retentionPolicies:()=>apiClient.request<{policies:RetentionPolicyDto[];deletionSummary:Array<{status:string;count:number}>}>("/admin/retention-policies"),
  retentionBindings:(visitId:string)=>apiClient.request<{items:RetentionBindingDto[]}>(`/visits/${visitId}/retention-bindings`),
  operationsHealth:()=>apiClient.request<OperationsHealthDto>("/admin/operations/health"),
  createRetentionPolicy:(body:{dataType:string;retentionDays:number;legalHoldSupported:boolean;effectiveFrom:string})=>apiClient.request<RetentionPolicyDto>("/admin/retention-policies",{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  createLegalHold:(visitId:string,reasonCode:string,reasonDetailRedacted:string)=>apiClient.request(`/admin/legal-holds/${visitId}`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({reasonCode,reasonDetailRedacted})}),
  releaseLegalHold:(visitId:string,reason:string)=>apiClient.request(`/admin/legal-holds/${visitId}`,{method:"DELETE",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({reason})}),
  approvals:()=>apiClient.request<List<ApprovalDto>>("/admin/content-approvals"),
  decideApproval:(body:Record<string,unknown>)=>apiClient.request("/admin/content-approvals",{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  approvalBatches:()=>apiClient.request<List<ApprovalBatchDto>&{candidates:ApprovalCandidateDto[]}>("/admin/content-approval-batches"),
  createApprovalBatch:(body:{type:string;category:string})=>apiClient.request<ApprovalBatchDto>("/admin/content-approval-batches",{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  decideApprovalBatch:(id:string,body:{decision:"approved"|"rejected";reason:string})=>apiClient.request<{id:string;status:string;approvalCount:number;requiredApprovals:number}>(`/admin/content-approval-batches/${id}/decisions`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify(body)}),
  analytics:()=>apiClient.request<{minimumCohort:number;groups:Array<{branchId:string;name:string;visitCount:number;reviewCount:number}>}>("/admin/analytics"),
  roleplayTurn:(scenarioId:string,messages:Array<{role:"staff"|"customer";text:string}>,sessionId?:string)=>apiClient.request<{sessionId:string;turnId:string;sequenceNo:number;customerReply:string;feedback:Array<{category:string;message:string}>;model:string;stored:true;contentPolicy:ContentPolicyDto}>("/training/roleplay-turns",{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({scenarioId,...(sessionId?{sessionId}:{}),messages})}),
  roleplaySessions:()=>apiClient.request<List<RoleplaySessionDto>>("/training/roleplay-sessions"),
  roleplaySession:(id:string)=>apiClient.request<RoleplaySessionDetailDto>(`/training/roleplay-sessions/${id}`),
  completeRoleplaySession:(id:string,selfNote:string)=>apiClient.request(`/training/roleplay-sessions/${id}/complete`,{method:"POST",headers:{"idempotency-key":apiClient.idempotencyKey()},body:JSON.stringify({selfNote})}),
};
