import {randomUUID} from "node:crypto";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import type {FastifyInstance} from "fastify";
import {HanamaruRepository,createPool,developmentIds} from "@hanamaru/database";
import {createLocalProviders} from "@hanamaru/platform";
import {buildApp} from "./app.js";
import {loadConfig} from "./config.js";

const databaseUrl=process.env.DATABASE_URL;
describe.skipIf(!databaseUrl)("visit product cards",()=>{
  let app:FastifyInstance;
  let repository:HanamaruRepository;
  const visitId=randomUUID();
  const keys:string[]=[];
  const productIds:string[]=[];
  const sourceObjectId=randomUUID(),sourceDocumentId=randomUUID(),sourceExtractionId=randomUUID();
  const headers=(key?:string)=>({"x-dev-role":"manager",...(key?{"idempotency-key":key}:{})});
  beforeAll(async()=>{
    repository=new HanamaruRepository(createPool(databaseUrl!));
    await repository.system("INSERT INTO visits(id,organization_id,branch_id,assigned_membership_id,case_number,status) VALUES($1,$2,$3,$4,$5,'draft')",[visitId,developmentIds.organizationId,developmentIds.branchId,developmentIds.membershipId,`PRODUCT-${visitId.slice(0,8)}`]);
    app=await buildApp({repository:new HanamaruRepository(createPool(databaseUrl!)),providers:createLocalProviders(),config:{...loadConfig({NODE_ENV:"test",ALLOW_DEV_AUTH:"true"}),port:0}});
  });
  afterAll(async()=>{
    await app?.close();
    if(repository){
      await repository.system("DELETE FROM visit_products WHERE id=ANY($1::uuid[])",[productIds]);
      await repository.system("DELETE FROM visit_field_values WHERE document_extraction_id=$1",[sourceExtractionId]);
      await repository.system("DELETE FROM document_extractions WHERE id=$1",[sourceExtractionId]);
      await repository.system("DELETE FROM visit_documents WHERE id=$1",[sourceDocumentId]);
      await repository.system("DELETE FROM storage_objects WHERE id=$1",[sourceObjectId]);
      await repository.system("DELETE FROM idempotency_records WHERE idempotency_key=ANY($1::varchar[])",[keys]);
      await repository.system("DELETE FROM visits WHERE id=$1",[visitId]);
      await repository.close();
    }
  });
  it("stores multiple cards, replays safely, and rejects stale updates or an inaccessible visit",async()=>{
    const firstKey=randomUUID();keys.push(firstKey);
    const firstBody={productName:"試験用の時計",quantity:2,conditionNote:"小傷あり",accessoriesNote:"箱あり"};
    const first=await app.inject({method:"POST",url:`/api/v1/visits/${visitId}/products`,headers:headers(firstKey),payload:firstBody});
    expect(first.statusCode).toBe(201);
    productIds.push(first.json().id);
    const replay=await app.inject({method:"POST",url:`/api/v1/visits/${visitId}/products`,headers:headers(firstKey),payload:firstBody});
    expect(replay.statusCode).toBe(201);
    expect(replay.json().id).toBe(first.json().id);
    const secondKey=randomUUID();keys.push(secondKey);
    const second=await app.inject({method:"POST",url:`/api/v1/visits/${visitId}/products`,headers:headers(secondKey),payload:{productName:"試験用のカメラ",quantity:1}});
    expect(second.statusCode).toBe(201);
    productIds.push(second.json().id);
    const list=await app.inject({method:"GET",url:`/api/v1/visits/${visitId}/products`,headers:headers()});
    expect(list.statusCode).toBe(200);
    expect(list.json().items.map((item:{id:string})=>item.id)).toEqual(expect.arrayContaining(productIds));
    const updateKey=randomUUID();keys.push(updateKey);
    const updated=await app.inject({method:"PATCH",url:`/api/v1/visits/${visitId}/products/${first.json().id}`,headers:headers(updateKey),payload:{...firstBody,quantity:3,expectedLockVersion:1}});
    expect(updated.statusCode).toBe(200);
    expect(updated.json()).toMatchObject({quantity:3,lockVersion:2});
    const staleKey=randomUUID();keys.push(staleKey);
    const stale=await app.inject({method:"PATCH",url:`/api/v1/visits/${visitId}/products/${first.json().id}`,headers:headers(staleKey),payload:{...firstBody,quantity:4,expectedLockVersion:1}});
    expect(stale.statusCode).toBe(409);
    const inaccessible=await app.inject({method:"GET",url:`/api/v1/visits/${randomUUID()}/products`,headers:headers()});
    expect(inaccessible.statusCode).toBe(404);
  });
  it("links a manually entered card only to a confirmed appraisal field on its visit",async()=>{
    const invalidKey=randomUUID();keys.push(invalidKey);
    const invalid=await app.inject({method:"POST",url:`/api/v1/visits/${visitId}/products`,headers:headers(invalidKey),payload:{productName:"匿名テスト品",quantity:1,sourceExtractionId:randomUUID()}});
    expect(invalid.statusCode).toBe(422);
    await repository.system("INSERT INTO storage_objects(id,organization_id,bucket_name,object_name,object_generation,purpose,status,mime_type,size_bytes,sha256) VALUES($1,$2,'test-bucket',$3,1,'visit_pdf','available','application/pdf',10,$4)",[sourceObjectId,developmentIds.organizationId,`organizations/${developmentIds.organizationId}/visits/${visitId}/documents/${sourceDocumentId}/source`,"0".repeat(64)]);
    await repository.system("INSERT INTO visit_documents(id,organization_id,visit_id,storage_object_id,status,uploaded_by_membership_id) VALUES($1,$2,$3,$4,'extracted',$5)",[sourceDocumentId,developmentIds.organizationId,visitId,sourceObjectId,developmentIds.membershipId]);
    const schema=await repository.system<{id:string}>("SELECT id FROM form_schema_versions WHERE organization_id=$1 AND schema_key='visit_info' AND status='active'",[developmentIds.organizationId]);
    expect(schema.rows).toHaveLength(1);
    await repository.system("INSERT INTO document_extractions(id,organization_id,visit_document_id,form_schema_version_id,version,status,provider,model_name) VALUES($1,$2,$3,$4,1,'confirmed','local','test')",[sourceExtractionId,developmentIds.organizationId,sourceDocumentId,schema.rows[0]!.id]);
    await repository.system("INSERT INTO visit_field_values(organization_id,document_extraction_id,field_key,value_type,text_value,verification_status) VALUES($1,$2,'appraisalItems','text','時計、カメラ','confirmed')",[developmentIds.organizationId,sourceExtractionId]);
    const unrelatedKey=randomUUID();keys.push(unrelatedKey);
    const unrelated=await app.inject({method:"POST",url:`/api/v1/visits/${visitId}/products`,headers:headers(unrelatedKey),payload:{productName:"時計",quantity:1,sourceExtractionId,sourceAppraisalExcerpt:"自動車"}});
    expect(unrelated.statusCode).toBe(422);
    const orphanKey=randomUUID();keys.push(orphanKey);
    const orphan=await app.inject({method:"POST",url:`/api/v1/visits/${visitId}/products`,headers:headers(orphanKey),payload:{productName:"時計",quantity:1,sourceAppraisalExcerpt:"時計"}});
    expect(orphan.statusCode).toBe(422);
    const validKey=randomUUID();keys.push(validKey);
    const card=await app.inject({method:"POST",url:`/api/v1/visits/${visitId}/products`,headers:headers(validKey),payload:{productName:"時計",quantity:1,sourceExtractionId,sourceAppraisalExcerpt:"時計"}});
    expect(card.statusCode).toBe(201);
    expect(card.json()).toMatchObject({productName:"時計",sourceExtractionId,sourceAppraisalExcerpt:"時計"});
    productIds.push(card.json().id);
    const listed=await app.inject({method:"GET",url:`/api/v1/visits/${visitId}/products`,headers:headers()});
    expect(listed.json().items).toEqual(expect.arrayContaining([expect.objectContaining({id:card.json().id,sourceExtractionId,sourceAppraisalExcerpt:"時計"})]));
  });
  it("keeps failed market research assigned and blocks judgment until the result is recorded",async()=>{
    const createKey=randomUUID();keys.push(createKey);
    const created=await app.inject({method:"POST",url:`/api/v1/visits/${visitId}/products`,headers:headers(createKey),payload:{productName:"相場未確定の匿名商品",quantity:1}});
    expect(created.statusCode).toBe(201);const productId=created.json().id as string;productIds.push(productId);
    const holdUrl=`/api/v1/visits/${visitId}/products/${productId}/research-hold`;
    const resumeUrl=`/api/v1/visits/${visitId}/products/${productId}/research-resume`;
    const holdBody={category:"no_candidates",reason:"比較できる候補がないため手動調査",expectedLockVersion:1};
    const holdKey=randomUUID();keys.push(holdKey);
    const held=await app.inject({method:"POST",url:holdUrl,headers:headers(holdKey),payload:holdBody});
    expect(held.statusCode).toBe(200);expect(held.json()).toMatchObject({status:"research_hold",researchHoldCategory:"no_candidates",researchHoldAssigneeId:developmentIds.managerMembershipId,lockVersion:2});
    const replay=await app.inject({method:"POST",url:holdUrl,headers:headers(holdKey),payload:holdBody});
    expect(replay.statusCode).toBe(200);expect(replay.json().lockVersion).toBe(2);
    const consultationKey=randomUUID();keys.push(consultationKey);
    const blocked=await app.inject({method:"POST",url:`/api/v1/visits/${visitId}/products/${productId}/consultations`,headers:headers(consultationKey),payload:{assignedManagerId:developmentIds.managerMembershipId,proposedPriceYen:1000,reason:"まだ調査中"}});
    expect(blocked.statusCode).toBe(409);
    const staleKey=randomUUID();keys.push(staleKey);
    const stale=await app.inject({method:"POST",url:resumeUrl,headers:headers(staleKey),payload:{resolutionNote:"候補を確認",expectedLockVersion:1}});
    expect(stale.statusCode).toBe(409);
    const otherKey=randomUUID();keys.push(otherKey);
    const other=await app.inject({method:"POST",url:resumeUrl,headers:{"x-dev-role":"assessor","idempotency-key":otherKey},payload:{resolutionNote:"担当外からの再開",expectedLockVersion:2}});
    expect(other.statusCode).toBe(403);
    const resumeKey=randomUUID();keys.push(resumeKey);
    const resumed=await app.inject({method:"POST",url:resumeUrl,headers:headers(resumeKey),payload:{resolutionNote:"型番を確認し手動で相場を調査した",expectedLockVersion:2}});
    expect(resumed.statusCode).toBe(200);expect(resumed.json()).toMatchObject({status:"draft",researchHoldResolutionNote:"型番を確認し手動で相場を調査した",lockVersion:3});
    const list=await app.inject({method:"GET",url:`/api/v1/visits/${visitId}/products`,headers:headers()});
    expect(list.statusCode).toBe(200);expect(list.json().items).toEqual(expect.arrayContaining([expect.objectContaining({id:productId,status:"draft",researchHoldAssigneeName:expect.any(String)})]));
  });
});
