import { createHash,randomUUID } from "node:crypto";
import { Readable } from "node:stream";
import { describe,expect,it } from "vitest";
import { acceptLocalUpload,acceptLocalUploadStream,createLocalProviders } from "./index.js";

describe("local providers",()=>{
  it("extracts every formal PoC visit field and ignores values outside the active schema",async()=>{
    const schema={type:"object",properties:Object.fromEntries(["visitDate","visitTime","customerLabel","appraisalItems","visitAddress","contact","parking","campaign","notes","assignedStaffName"].map(key=>[key,{type:"string"}]))};
    const result=await createLocalProviders().ai.extract({text:"訪問予定日: 2026-08-20 訪問予定時間: 14:00 お客様表示名: 匿名顧客A 査定品: バッグ2点 住所: 東京都サンプル区1-2-3 連絡先: 登録済み番号 駐車場: 敷地内1台 キャンペーン: 夏季案内 備考: 査定のみ希望 担当: デモ査定員 unknownField: 保存しない",schema});
    expect(Object.fromEntries(result.fields.map(field=>[field.key,field.value]))).toEqual({visitDate:"2026-08-20",visitTime:"14:00",customerLabel:"匿名顧客A",appraisalItems:"バッグ2点",visitAddress:"東京都サンプル区1-2-3",contact:"登録済み番号",parking:"敷地内1台",campaign:"夏季案内",notes:"査定のみ希望",assignedStaffName:"デモ査定員"});
    expect(result.fields.every(field=>field.key in schema.properties)).toBe(true);
  });
  it("resolves the stored generation while verifying an upload declaration",async()=>{ const body=Buffer.from("safe test"); const sha=createHash("sha256").update(body).digest("hex");const objectName=`upload-${randomUUID()}`; const input={organizationId:"org",objectName,mimeType:"text/plain",sizeBytes:body.length,sha256:sha,expiresAt:new Date(Date.now()+1000)}; acceptLocalUpload(objectName,input,body); const p=createLocalProviders();await expect(p.storage.verify(input)).resolves.toMatchObject({sha256:sha,generation:"1"});await p.storage.delete(objectName,"1"); const review=await p.ai.review({transcript:"test",segments:[{id:"s1",text:"test"}]}); expect(review.findings.map(f=>f.category)).toEqual(["strength","improvement","talk","compliance","next_action","revisit"]); });
  it("streams local uploads while enforcing the declared size and digest",async()=>{const body=Buffer.from("streamed upload");const objectName=`upload-stream-${randomUUID()}`;const input={organizationId:"org",objectName,mimeType:"application/pdf",sizeBytes:body.length,sha256:createHash("sha256").update(body).digest("hex"),expiresAt:new Date(Date.now()+1000)};await acceptLocalUploadStream(input.objectName,input,Readable.from([body.subarray(0,5),body.subarray(5)]));const storage=createLocalProviders().storage;await expect(storage.verify(input)).resolves.toMatchObject({sizeBytes:body.length,sha256:input.sha256});const badName=`upload-stream-bad-${randomUUID()}`;await expect(acceptLocalUploadStream(badName,{...input,objectName:badName,sha256:"0".repeat(64)},Readable.from([body]))).rejects.toThrow("CHECKSUM_MISMATCH");await storage.delete(objectName,"1");});
  it("refuses to overwrite and removes an incomplete write-once local object",async()=>{const body=Buffer.from("write once");const objectName=`write-once-${randomUUID()}`;const input={organizationId:"org",objectName,mimeType:"text/plain",sizeBytes:body.length,sha256:createHash("sha256").update(body).digest("hex"),expiresAt:new Date(Date.now()+1000)};acceptLocalUpload(objectName,input,body);expect(()=>acceptLocalUpload(objectName,input,body)).toThrow(/EEXIST/);const storage=createLocalProviders().storage;await storage.deleteIncompleteUpload(objectName);await expect(storage.verify(input)).rejects.toThrow(/ENOENT/);});
  it("returns only strict quality flags with evidence from the supplied segments",async()=>{const ai=createLocalProviders().ai;const clear=await ai.assessTranscriptQuality({durationMs:1000,segments:[{id:"s1",startMs:0,endMs:1000,speakerLabel:"chunk-000:1",text:"査定額をご説明します"}]});expect(clear.flags).toEqual([]);const media=await ai.assessTranscriptQuality({durationMs:1000,segments:[{id:"s2",startMs:0,endMs:1000,speakerLabel:"chunk-000:1",text:"ここからニュース番組です"}]});expect(media.flags).toEqual([{type:"possible_media",confidence:.95,evidenceSegmentIds:["s2"]}]);});
});
