import {describe,expect,it} from "vitest";
import {normalizeReviewOutput,normalizeRoleplayOutput,parseModelJson} from "./model-output.js";

const complianceChecks={
  notification:{status:"compliant",detail:"業者名と目的を説明",evidenceSegmentIds:["segment-1"]},
  coolingOff:{status:"unclear",detail:"8日間の説明が不十分",evidenceSegmentIds:["segment-1"]},
  documentDelivery:{status:"noncompliant",detail:"書面交付を確認できない",evidenceSegmentIds:["segment-1"]},
  pressureSelling:{status:"compliant",detail:"判断を急がせていない",evidenceSegmentIds:["segment-1"]},
};

describe("model output boundary",()=>{
  it("requires all six review areas and evidence for each",()=>{const findings=["strength","improvement","talk","compliance","next_action","revisit"].map(category=>({category,title:category,description:"説明",recommendedAction:null,evidenceSegmentIds:["segment-1"]}));expect(normalizeReviewOutput({summary:"概要",findings,complianceChecks},"model").findings).toHaveLength(6);expect(()=>normalizeReviewOutput({summary:"概要",findings:findings.slice(1),complianceChecks},"model")).toThrow(/missing review category/);expect(()=>normalizeReviewOutput({summary:"概要",findings:findings.map((finding,index)=>index?finding:{...finding,evidenceSegmentIds:[]}),complianceChecks},"model")).toThrow(/missing review evidence strength/);});
  it("requires and returns only the selected review areas",()=>{const findings=[{category:"strength",title:"良かった点",description:"説明",recommendedAction:null,evidenceSegmentIds:["segment-1"]},{category:"compliance",title:"法令",description:"確認",recommendedAction:null,evidenceSegmentIds:["segment-1"]}];const output=normalizeReviewOutput({summary:"概要",findings,complianceChecks},"model",["strength","compliance"]);expect(output.findings.map(finding=>finding.category)).toEqual(["strength","compliance"]);expect(output.findings.find(finding=>finding.category==="compliance")?.description).toBe("告知: ✅ 業者名と目的を説明\nクーリングオフ: ⚠️ 8日間の説明が不十分\n書面交付: ❌ 書面交付を確認できない\n押し買い: ✅ 判断を急がせていない");expect(()=>normalizeReviewOutput({summary:"概要",findings:findings.slice(0,1),complianceChecks},"model",["strength","compliance"])).toThrow(/missing review category compliance/);});
  it("rejects a generic compliance finding without the four structured checks",()=>{const findings=[{category:"compliance",title:"法令",description:"告知について確認",recommendedAction:null,evidenceSegmentIds:["segment-1"]}];expect(()=>normalizeReviewOutput({summary:"概要",findings},"model",["compliance"])).toThrow(/missing review compliance checks/);});
  it("normalizes the PoC review contract without losing its compliance and revisit rubric",()=>{const output=normalizeReviewOutput({summary:"概要",good:"丁寧に説明した",bad:"意思確認を早める",talks:[{scene:"金額提示",talk:"査定根拠をご説明します",evidenceSegmentIds:["s1"]}],compliance:{告知:"✅ 業者名と目的を説明",クーリングオフ:"⚠️ 8日間の説明が不十分",書面交付:"❌ 書面交付を確認できない",押し買い:"✅ 判断を急がせていない"},complianceEvidence:{告知:["s1"],クーリングオフ:["s2"],書面交付:["s2"],押し買い:["s3"]},advice:"次回は書面を示しながら説明してください。確認の質問も加えてください。",revisit:{score:"高",reason:"お客様が来週の再訪に合意した",patterns:["次回合意あり"],evidenceSegmentIds:["s3"]},evidence:{good:["s1"],bad:["s2"],advice:["s2"]}},"model");expect(output.findings).toHaveLength(6);expect(output.findings.find(finding=>finding.category==="talk")?.description.split("\n")).toHaveLength(1);expect(output.findings.find(finding=>finding.category==="compliance")?.description).toContain("クーリングオフ: ⚠️");expect(output.findings.find(finding=>finding.category==="revisit")?.title).toContain("高");});
  it("rejects incomplete PoC compliance output and unsupported revisit scores",()=>{const base={good:"良い",bad:"改善",talks:[{scene:"場面",talk:"トーク",evidenceSegmentIds:["s1"]}],compliance:{告知:"✅ 済",クーリングオフ:"✅ 済",書面交付:"✅ 済",押し買い:"✅ 問題なし"},complianceEvidence:{告知:["s1"],クーリングオフ:["s1"],書面交付:["s1"],押し買い:["s1"]},advice:"次回も確認する。丁寧に進める。",revisit:{score:"高",reason:"合意",patterns:["次回合意あり"],evidenceSegmentIds:["s1"]},evidence:{good:["s1"],bad:["s1"],advice:["s1"]}};expect(()=>normalizeReviewOutput({...base,compliance:{...base.compliance,告知:"済"}},"model")).toThrow(/invalid compliance status/);expect(()=>normalizeReviewOutput({...base,revisit:{...base.revisit,score:"最高"}},"model")).toThrow(/invalid revisit score/);});
  it("rejects ranking fields, empty feedback, and invalid JSON",()=>{expect(()=>normalizeRoleplayOutput({customerReply:"返答",feedback:[],score:100},"model")).toThrow(/ranking/);expect(()=>normalizeRoleplayOutput({customerReply:"返答",feedback:[]},"model")).toThrow(/missing roleplay feedback/);expect(()=>parseModelJson("not-json")).toThrow(/invalid JSON/);});
});
